on: 
 push:
  branches: master
 
permissions: write-all
jobs:
  build:
    name: Publish site
    runs-on: ubuntu-latest
    steps:
     - uses: nixbuild/nix-quick-install-action@v21
       with:
        nix_conf: experimental-features = nix-command flakes
     - name: Checkout main
       uses: actions/checkout@v3.0.0
     - name: build
       run: |
        nix build
        cp --recursive --dereference --no-preserve=mode,ownership result ownresult
      
     - name: Setup Pages
       uses: actions/configure-pages@v2
     - name: Upload artifact
       uses: actions/upload-pages-artifact@v1
       with:
        # Upload built files
        path: './ownresult'
     - name: Deploy to GitHub Pages
       id: deployment
       uses: actions/deploy-pages@v1
